Update build_platformio_xiao_motor.yaml

diff --git a/.github/workflows/build_platformio_xiao_motor.yaml b/.github/workflows/build_platformio_xiao_motor.yaml
--- a/.github/workflows/build_platformio_xiao_motor.yaml
+++ b/.github/workflows/build_platformio_xiao_motor.yaml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: Compile ESP32 Platformio (xiao motor board)
+name: Compile ESP32 Platformio (xiao led ring board)
 
 # Controls when the action will run. Triggers the workflow on push or pull request
 # events but only for the master branch
@@ -53,21 +53,28 @@ jobs:
     - name: merge into one binary
       run: |
         dir .pio/build/UC2_3_Xiao_Slave_Motor/ 
-        mv .pio/build/UC2_3_Xiao_Slave_Motor/*.bin builds3/
-        cd builds3
-        python -m esptool --chip esp32s3 merge_bin  -o UC2_3_Xiao_Slave_Motor.bin  --flash_mode dio  --flash_freq 40m  --flash_size 4MB  0x1000 bootloader.bin  0x8000 partitions.bin  0xe000 boot_app0.bin  0x10000 firmware.bin
+        cd .pio/build/UC2_3_Xiao_Slave_Motor/
+        python -m esptool --chip esp32s3 merge_bin  -o UC2_3_Xiao_Slave_Motor.bin  --flash_mode dio  --flash_freq 40m  --flash_size 4MB 0x0000 bootloader.bin  0x8000 partitions.bin  0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin  0x10000 firmware.bin
+    - name: Debug merged firmware
+      run: ls -l .pio/build/UC2_3_Xiao_Slave_Motor/
 
+    - name: Check for merged firmware
+      run: |
+        if [ ! -f .pio/build/UC2_3_Xiao_Slave_Motor/UC2_3_Xiao_Slave_Motor.bin ]; then
+          echo "Merged firmware binary not found!"
+          exit 1
+        fi
     - uses: actions/upload-artifact@v3
       with:
         name: merged-firmware
-        path: builds3/UC2_3_Xiao_Slave_Motor.bin
+        path: .pio/build/UC2_3_Xiao_Slave_Motor/UC2_3_Xiao_Slave_Motor.bin
 
     - name: Push to youseetoo Webtool
       uses: dmnemec/copy_file_to_another_repo_action@main
       env:
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
       with:
-        source_file: 'builds3/UC2_3_Xiao_Slave_Motor.bin'
+        source_file: '.pio/build/UC2_3_Xiao_Slave_Motor/UC2_3_Xiao_Slave_Motor.bin'
         destination_repo: 'youseetoo/youseetoo.github.io'
         destination_folder: 'static/firmware_build'
         user_email: 'bene.d@gmx.de'
