Update build_platformio_xiao_ledring.yaml

diff --git a/.github/workflows/build_platformio_xiao_ledring.yaml b/.github/workflows/build_platformio_xiao_ledring.yaml
--- a/.github/workflows/build_platformio_xiao_ledring.yaml
+++ b/.github/workflows/build_platformio_xiao_ledring.yaml
@@ -56,6 +56,16 @@ jobs:
         cd .pio/build/seeed_xiao_esp32s3_ledring/
         python -m esptool --chip esp32s3 merge_bin  -o seeed_xiao_esp32s3_ledring.bin  --flash_mode dio  --flash_freq 40m  --flash_size 4MB 0x0000 bootloader.bin  0x8000 partitions.bin  0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin  0x10000 firmware.bin
 
+    - name: Debug merged firmware
+      run: ls -l .pio/build/seeed_xiao_esp32s3_ledring/
+
+    - name: Check for merged firmware
+      run: |
+        if [ ! -f .pio/build/seeed_xiao_esp32s3_ledring.bin ]; then
+          echo "Merged firmware binary not found!"
+          exit 1
+        fi
+
     - uses: actions/upload-artifact@v3
       with:
         name: merged-firmware
